# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c0ee6215af22d704aa4e0ac322e9151bbe002501bf9e3ff80e74f453a2ab38a078ce7760c4177e59d4c35b44a55c7858765a3e2eb37baa5ca520ba1e1d855d6

test:
  secret_key_base: 21f0dcf230b3a112f817c4d5b9f2504c43001728927d5d7f397d6cc3f1a72b4b2fb50e3b2862aa3a0d331b237b0da88396c78c9ca1c09e542058a8d6e3aca44e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
