class CreateWinSecurityLogs < ActiveRecord::Migration[5.0]
  def change
    create_table :win_security_logs do |t|

      t.text    'action'
      t.text    'ActivityID'
      t.text    'AuthenticationPackageName'
      t.text    'CallerProcessId'
      t.text    'CallerProcessName'
      t.text    'Category'
      t.text    'Channel'
      t.text    'controller'
      t.text    'ElevatedToken'
      t.datetime  'EventTime'
      t.integer   'EventID'
      t.text    'EventType'
      t.datetime  'EventReceivedTime'
      t.text    'Hostname'
      t.text    'ImpersonationLevel'
      t.text    'IpAddress'
      t.text    'IpPort'
      t.text    'KeyLength'
      t.text    'Keywords'
      t.text    'LmPackageName'
      t.text    'LogonGuid'
      t.text    'LogonType'
      t.text    'LogonProcessName'
      t.text    'MandatoryLabel'
      t.text      'Message'
      t.text    'NewProcessId'
      t.text    'NewProcessName'
      t.datetime  'NewTime'
      t.text    'Opcode'
      t.integer   'OpcodeValue'
      t.text    'param1'
      t.text    'param2'
      t.text    'param3'
      t.text    'param4'
      t.text    'param5'
      t.text    'param6'
      t.text    'param7'
      t.text    'ParentProcessName'
      t.datetime  'PreviousTime'
      t.text      'PrivilegeList'
      t.integer   'ProcessID'
      t.text    'ProcessName'
      t.text    'ProviderGuid'
      t.text    'PuaCount'
      t.text    'PuaPolicyId'
      t.integer   'RecordNumber'
      t.text    'RestrictedAdminMode'
      t.integer   'SeverityValue'
      t.text    'Severity'
      t.text    'SourceModuleName'
      t.text    'SourceModuleType'
      t.text    'SourceName'
      t.text    'SubjectDomainName'
      t.text    'SubjectLogonId'
      t.text    'SubjectUserName'
      t.text    'SubjectUserSid'
      t.text    'TargetDomainName'
      t.text    'TargetInfo'
      t.text    'TargetLinkedLogonId'
      t.text    'TargetLogonGuid'
      t.text    'TargetLogonId'
      t.text    'TargetOutboundDomainName'
      t.text    'TargetOutboundUserName'
      t.text    'TargetServerName'
      t.text    'TargetSid'
      t.text    'TargetUserName'
      t.text    'TargetUserSid'
      t.integer   'Task'
      t.integer   'ThreadID'
      t.text    'TokenElevationType'
      t.text    'TransmittedServices'
      t.integer   'Version'
      t.text    'VirtualAccount'
      t.text      'win_eventlog'
      t.text    'WorkstationName'

      t.timestamps
    end
  end
end
